### PR TITLE
Use nice link from n-navigation

### PR DESCRIPTION
**Pull request by TheoLeanse**
/cc @aintgoin2goa @i-like-robots @matthew-andrews @adambraimbridge 

and it's definitely `navigation.lists` not `navigationLists`?

### CODE REVIEW

**Comment by i-like-robots** [comment]
+1

**Comment by aintgoin2goa** [comment]
They both work - but navigationLists is depreacted

**Comment by adambraimbridge** [comment]
👍

**Comment by leggsimon** [comment]
+1

**Pull request merged**
