### PR TITLE
Try Mouseflow (instead of Inspectlet)

### PR DESCRIPTION
**Pull request by commuterjoy**
@adambraimbridge @lc512k

### CODE REVIEW

**Comment by lc512k** [comment]
@commuterjoy signed up for a free account to test with

**Comment by commuterjoy** [comment]
@lc512k i did :)

**Comment by lc512k** [comment]
I like their popular heatmaps section. I don't know if inspectlet provides something similar.

**Comment by lc512k** [comment]
Form analytics: https://mouseflow.zendesk.com/hc/en-us/articles/207492486-Form-Analytics
Good stuff

**Pull request merged**
