### PR TITLE
Removed code for 'timeOnPage' event

### PR DESCRIPTION
**Pull request by adambraimbridge**
🐿 v2.8.0

### CODE REVIEW

**Comment by benbarnett** [comment]
I think there's a spec file somewhere too @adambraimbridge 👍

**Comment by adambraimbridge** [comment]
Thanks @benbarnett, so there is. Odd that removing the code hasn't failed the tests ... :)

**Comment by benbarnett** [comment]
That is a point of the upmost excellence. Hmm!

**Comment by adambraimbridge** [comment]
Hahahah :)

**Pull request merged**
