### PR TITLE
display flex helper

### PR DESCRIPTION
**Pull request by wheresrhys**
nicked from myft-page @i-like-robots

### CODE REVIEW

**Comment by i-like-robots** [comment]
I wonder if this can be dealt with by autoprefixer?

**Comment by i-like-robots** [comment]
Just wondering if we'd also want to apply this to the grid and any other use of `display: flex`?

**Comment by wheresrhys** [comment]
~~Nope. It took a lot of hackery to do this. Working around autoprefixer was half the problem. It does all the prefixes https://github.com/postcss/autoprefixer#flexbox-filters-etc~~

It looks like they have indeed fixed it! added a `flexbox: "no-2009"` option https://github.com/postcss/autoprefixer/commit/b6d228fe4b5fc6f326d5bc80d0300ca157147db7, https://github.com/postcss/autoprefixer#disabling. This will need careful coordination with origami cc @aelias

**Comment by i-like-robots** [comment]
So this would make the following non-flexi:

- Android 4.3
- BB7
- iOS6

That's probably OK...

**Comment by wheresrhys** [comment]
We deliberately suppress flexbox (where we remember to) in those browsers as it is totally broken. Twas the cause of all the pain in taking over m.ft.com traffic in december if you recall

**Comment by wheresrhys** [comment]
closed in favour of https://github.com/Financial-Times/n-makefile/pull/86

**Pull request closed without merging**
