### PR TITLE
add IntersectionObserver polyfill

### PR DESCRIPTION
**Pull request by VladDubrovskis**
IntersectionObserver polyfill has been released in polyfill.io v3.8.0

URL to verify:
`https://next-geebee.ft.com/polyfill/v2/polyfill.js?callback=ftNextPolyfillServiceCallback&features=default,requestAnimationFrame,Promise,matchMedia,HTMLPictureElement,CustomEvent%7Calways%7Cgated,fetch%7Calways%7Cgated,Array.prototype.find%7Calways%7Cgated,Array.prototype.findIndex%7Calways%7Cgated,IntersectionObserver%7Calways%7Cgated&excludes=Symbol,Symbol.iterator,Symbol.species,Map,Set`

/cc @adgad

### CODE REVIEW

**Comment by wheresrhys** [comment]
why `always|gated` ?

**Comment by VladDubrovskis** [comment]
always: cause only included in Chrome 51
gated: so we do not replace it with polyfill when the browsers start rolling it out?

But also a high chance of a bit of copy/paste

**Comment by VladDubrovskis** [comment]
@wheresrhys about to merge and release this. Is patch release good for this?

**Comment by andrewgeorgiou1981** [comment]
👍

**Pull request merged**
