### PR TITLE
add Speedcurve LUX

### PR DESCRIPTION
**Pull request by bjfletcher**
🐿 v2.6.0

### CODE REVIEW

**Comment by wheresrhys** [comment]
On the previous attempt to add it (when we tried the alpha) there was also an inline script. https://github.com/Financial-Times/n-ui/pull/377/files 

Is that not needed these days?

**Comment by bjfletcher** [comment]
@wheresrhys wow that's some mad inline code in the early days... yup, seems like they've since improved

https://speedcurve.com/features/lux/#snippet says just the LUX config object is needed.

**Comment by bjfletcher** [comment]
@wheresrhys ok, I think I have covered everything...
put in inline code from Speedcurve for mark/measure functions
this inline code is in a file of its own, meaning it's easier for me to get the linters/coveralls to ignore this file (it breaks many rules!)

**Comment by wheresrhys** [comment]
Isn't the point with the inline code though that it has to be inlined in the html?

**Comment by bjfletcher** [comment]
@wheresrhys hopefully no - if it doesn't work, we can figure out how to set it up so that it gets run sooner

**Comment by bjfletcher** [comment]
(unless you think we should put the JS directly into the HTML, although that's a bit messy IMHO)

**Comment by sjparkinson** [comment]
Closing because #1142 was merged.

**Pull request closed without merging**
