### PR TITLE
first stab at an n-ui build tool

### PR DESCRIPTION
**Pull request by wheresrhys**

### CODE REVIEW

**Comment by leggsimon** [comment]
What problem does this solve?

**Comment by leggsimon** [comment]
so it'll make our local builds much faster?

**Comment by wheresrhys** [comment]
that's one of the perks. 

reflecting on it, the main reason is to encapsulate all of n-ui's business in n-ui. No worrying about needing to coordinate some change with a related change in a build tool. If it's all in one repo then it's easier to reason about and manage

**Comment by wheresrhys** [comment]
Well, it's an opt-in, so just gonna merge. If it a hinderance people can scream at me

**Pull request merged**
