### PR TITLE
use polyfill.io v3

### PR DESCRIPTION
**Pull request by leggsimon**
Uses v3 of the polyfill service which introduces updated polyfills and improved cache hits

### CODE REVIEW

**Comment by i-like-robots** [comment]
Has this been tested in various browsers? Thinking specifically about IE11 which requires the most polyfilling

**Comment by leggsimon** [comment]
I haven't tested it at all. Jake assures me that it will have exactly the same behaviour (and that under the hood we are actually using v3 already)

**Comment by JakeChampion** [comment]
The change in this pull-request will make the polyfill-service use the latest version of the polyfills, which is likely something you would want to test across browsers. If you wanted to use the same polyfills as v2 you need to add a `version` query parameter set to `3.25.1`.

**Comment by i-like-robots** [comment]
I'll pick this up today for testing so we can get it over the line 🏁

**Comment by i-like-robots** [comment]
Tested in IE11 across two apps (search and video) and it was well

**Comment by leggsimon** [comment]
Thank you very much Matt!! 🙇

**Pull request merged**
