### PR TITLE
Removed logic for 'nUiExcludes' because nothing uses it

### PR DESCRIPTION
**Pull request by adambraimbridge**
image

I can't find any example of a `nUiExcludes` property, so I'm simplifying the code

### CODE REVIEW

**Comment by adgad** [comment]
Out of curiosity, what does nUiExcludes actually do?

**Comment by leggsimon** [comment]
If I remember correctly, nUiExternals is a way you can define an "external" usage of a module. Normally, when n-ui builds an app’s JS if it sees a `require('o-date')` for example it'll strip it out and use `window.FT.nUi._hiddenComponents.oDate` instead. This is so that, for some modules we only have one version knocking about but if for whatever reason an app needed to use a specific version of o-date it could define that it is "external".

I'm not sure whether we want to get rid of this option...

**Comment by adambraimbridge** [comment]
Thinking about it now, if we could understand the actual problem that is solved by `nUiExternals` (aka `webpack-externals)`,  we'd be in a better position to judge whether the solution is still required, and whether we can improve upon it. And of course document it a little better.

**Comment by leggsimon** [comment]
🤦‍♂️ I just realised I didn't answer your question @adgad. I'm almost certain there was a reason for having it but I can't remember what it was. @wheresrhys may remember...

**Pull request merged**
