### PR TITLE
use o-video 2.x

### PR DESCRIPTION
**Pull request by i-like-robots**
\0/

CC https://github.com/Financial-Times/n-card/pull/188 and https://github.com/Financial-Times/next-front-page/pull/1041

### CODE REVIEW

**Comment by i-like-robots** [comment]
better caching @wheresrhys  ?

**Comment by wheresrhys** [comment]
there's an o-video 2 already?!! what's new.

You prob need to be careful to remove bower resolutions etc for o-video in other apps

**Comment by i-like-robots** [comment]
Yep that's the tangle we're working out now... new stuff: https://github.com/Financial-Times/o-video/pull/45

**Comment by i-like-robots** [comment]
o-video usage in Next to be updated/checked:

- [ ] https://github.com/Financial-Times/next-stream-page/blob/master/client/components/video-stream/card.html
- [ ] https://github.com/Financial-Times/n-content-transform/blob/master/server/video-brightcove.js
- [ ] https://github.com/Financial-Times/next-article/blob/master/client/main.js
- [ ] https://github.com/Financial-Times/next-stream-page/blob/master/client/components/video-stream/index.js
- [ ] https://github.com/Financial-Times/next-stream-page/blob/master/shared/components/card-open-in-stream/inline-article/index.js

**Pull request merged**
