### PR TITLE
Slightly more optimal CTM

### PR DESCRIPTION
**Pull request by adgad**
Very minor optimisation, but constructing a blob is up to 1000 times slower than `typeof Blob (https://jsperf.com/blobs), and evaluating this sometimes takes up to 40ms.

screen shot 2018-02-21 at 16 08 58

(note: need to check that Blob isn't still a function in Android 4 - which is what this test was designed to exclude)

### CODE REVIEW

**Comment by i-like-robots** [comment]
-1000%

**Comment by leggsimon** [comment]
Hmm, I'm not sure whether this will work. I seem to remember that `Blob()` works in Android but `new Blob` doesn't. That was why it was in the try/catch, so that it would catch the error of calling new.

**Comment by adgad** [comment]
You are correct. New proposal:

https://caniuse.com/#feat=pagevisibility

`'visibilityState' in document`

**Comment by adgad** [comment]
Pushed a simpler CTM. Tested on browsers below (tick = CTM, no tick = doesn't CTM)


- [ ] Android 4.4 Browser 
- [ ] Android 4.4 Chrome
- [ ] iOS Safari 10 - 
- [ ] Edge
- [ ] Chrome (latest)
- [ ] Firefox (latest + 48)
- [ ] Desktop Safari(11 and 9)
- [ ] IE11
- [ ] IE10

**Comment by adgad** [comment]
https://jsperf.com/ft-ctm comparison of the two

**Comment by adambraimbridge** [comment]
image
Whoa

**Comment by leggsimon** [comment]
This looks like it'll still pass for Android 4.4 & 4.4.4? Is that right?

**Comment by adgad** [comment]
Nope - visibilityState is prefixed with `webkit` in android 4.4

**Pull request merged**
