### PR TITLE
Add Bower config with ignored dependencies 

### PR DESCRIPTION
**Pull request by i-like-robots**
Let's see if this can break the cyclical dependency on n-ui.

### CODE REVIEW

**Comment by wheresrhys** [comment]
:+1:

How you planning on testing it out?

**Comment by i-like-robots** [comment]
I cleared the Bower dependencies for streams and articles, linked n-ui in then continued with the full install. Both installed then built successfully. Any other ideas? I'm seeing if I can get n-ui to build locally, with a custom webpack config it's fine.

**Comment by wheresrhys** [comment]
maybe point bower.json for either of those apps at 'n-ui: #matth/break-the-cycle'

**Comment by i-like-robots** [comment]
All good

**Comment by wheresrhys** [comment]
:+1:

**Pull request merged**
